// This is a file to track version control information. It is autogenerated by
// the build bot. **** DO NOT CHANGE WITHOUT THE EXPLICIT CONSENT OF CRAZYCASTA

#ifndef VCREV_H
#define VCREV_H

const char* const vcRev_revString = "Unofficial build";
const int vcRev_revNumber = -1;

#endif